"""initial migration

Revision ID: 54b2ace0c0e3
Revises: 431f3817f727
Create Date: 2015-11-26 01:15:32.590000

"""

# revision identifiers, used by Alembic.
revision = '54b2ace0c0e3'
down_revision = '431f3817f727'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
