"""initial migration

Revision ID: 57c1f5e64a79
Revises: 25e9ccaffb5f
Create Date: 2015-11-26 02:35:04.111000

"""

# revision identifiers, used by Alembic.
revision = '57c1f5e64a79'
down_revision = '25e9ccaffb5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
